
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - image: mmassolit/user
          name: user
          ports:
            - containerPort: 8082
              name: user
          env:
            - name: POSTGRES_ENDPOINT
              value: "jdbc:postgresql://127.0.0.1:5432/user_service"
            - name: POSTGRES_PASSWORD
              value: "123"
            - name: POSTGRES_USERNAME
              value: "video_sharing_test"